version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: gomod
    directory: /jsonrpcfiber
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: gomod
    directory: /jsonrpcfiberv3
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: gomod
    directory: /benchmarks
    schedule:
      interval: monthly
    groups:
      competitors:
        patterns: ["*"]
